name: Dawarich
version: 0.2.0
slug: dawarich
description: Self-hostable alternative to Google Location History (Google Maps Timeline)
url: https://github.com/abloemert/hass-addon-dawarich.git
arch:
- amd64
- aarch64
homeassistant_api: true
auth_api: true
ports:
  3000/tcp: 10555
watchdog: http://[HOST]:[PORT:3000]/api/v1/health
panel_icon: mdi:map-marker
panel_title: Dawarich
panel_admin: false
init: false
options:
  db_host: 77b2833f-timescaledb
  db_user: postgres
  db_pass: homeassistant
  db_name: dawarich
schema:
  db_host: str
  db_user: str
  db_pass: password
  db_name: str

